name: Yawnlog
options:
  bundleIdPrefix: com.shimondeitel.fatiguelog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Yawnlog:
    type: application
    platform: iOS
    sources:
      - path: Yawnlog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.fatiguelog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Yawnlog/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  YawnlogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: YawnlogTests
      - path: Yawnlog.storekit
    dependencies:
      - target: Yawnlog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.fatiguelog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  YawnlogUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: YawnlogUITests
    dependencies:
      - target: Yawnlog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.fatiguelog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Yawnlog:
    build:
      targets:
        Yawnlog: all
        YawnlogTests: [test]
        YawnlogUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Yawnlog.storekit
    test:
      config: Debug
      storeKitConfiguration: Yawnlog.storekit
      targets:
        - YawnlogTests
        - YawnlogUITests
    archive:
      config: Release
